/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thinethra;

import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author XeNNoN
 */
public class registration extends javax.swing.JFrame {

    private String newpath = "-";

    /**
     * Creates new form registration
     */
    public registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        fb_id = new javax.swing.JTextField();
        fb_name = new javax.swing.JTextField();
        fb_nic_nam = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        school = new javax.swing.JTextField();
        hi_schhool = new javax.swing.JTextField();
        univer = new javax.swing.JTextField();
        grad = new javax.swing.JTextField();
        born = new javax.swing.JTextField();
        disc = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        loca = new javax.swing.JTextField();
        Occup = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        re_name = new javax.swing.JTextField();
        re_fb_id = new javax.swing.JTextField();
        re_type = new javax.swing.JTextField();
        re_link = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        fri = new javax.swing.JTextField();
        political = new javax.swing.JTextField();
        nati = new javax.swing.JTextField();
        etha = new javax.swing.JTextField();
        reli = new javax.swing.JTextField();
        tami_ca = new javax.swing.JTextField();
        muslim_scep = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        whats_app_link = new javax.swing.JTextField();
        viber_link = new javax.swing.JTextField();
        twitter_link = new javax.swing.JTextField();
        insta_link = new javax.swing.JTextField();
        snap_link = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        fb_ima = new javax.swing.JTextField();
        fb_pa = new javax.swing.JTextField();
        fb_video = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel45 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1315, 1830));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setForeground(new java.awt.Color(102, 153, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1315, 1830));
        jPanel1.setPreferredSize(new java.awt.Dimension(1315, 1830));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTER MEMBER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Facce Book ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Face Book Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Face Book Nick Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact Number");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Schools");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("High schools");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("University");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Graduate");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Born Country");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Distric/State");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Current city");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Locations");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Occupations");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 670, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Married/Unmarried");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 710, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Year");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 750, -1, -1));
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 750, 300, -1));

        fb_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_idActionPerformed(evt);
            }
        });
        jPanel1.add(fb_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 300, -1));

        fb_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_nameActionPerformed(evt);
            }
        });
        jPanel1.add(fb_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 300, -1));

        fb_nic_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_nic_namActionPerformed(evt);
            }
        });
        jPanel1.add(fb_nic_nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 300, -1));

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 300, -1));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 300, -1));

        school.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolActionPerformed(evt);
            }
        });
        jPanel1.add(school, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 300, -1));

        hi_schhool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hi_schhoolActionPerformed(evt);
            }
        });
        jPanel1.add(hi_schhool, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 300, -1));

        univer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                univerActionPerformed(evt);
            }
        });
        jPanel1.add(univer, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 300, -1));

        grad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradActionPerformed(evt);
            }
        });
        jPanel1.add(grad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 300, -1));

        born.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bornActionPerformed(evt);
            }
        });
        jPanel1.add(born, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 300, -1));

        disc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discActionPerformed(evt);
            }
        });
        jPanel1.add(disc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 300, -1));

        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 300, -1));

        loca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locaActionPerformed(evt);
            }
        });
        jPanel1.add(loca, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 630, 300, -1));

        Occup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OccupActionPerformed(evt);
            }
        });
        jPanel1.add(Occup, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 670, 300, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Married", "Unmarried" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 710, 300, -1));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Member", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 570, 690));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Relative Name");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Relative face book ID ");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Relative Type");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Relative links");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, -1, -1));

        re_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re_nameActionPerformed(evt);
            }
        });
        jPanel1.add(re_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 200, 280, -1));

        re_fb_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re_fb_idActionPerformed(evt);
            }
        });
        jPanel1.add(re_fb_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, 280, -1));

        re_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re_typeActionPerformed(evt);
            }
        });
        jPanel1.add(re_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, 280, -1));

        re_link.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re_linkActionPerformed(evt);
            }
        });
        jPanel1.add(re_link, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 280, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relative Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 530, 210));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Friends");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Political View");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Nationality");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Ethancity");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Religion");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Tamil Cast");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 580, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Muslim Scep");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 620, -1, -1));

        fri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friActionPerformed(evt);
            }
        });
        jPanel1.add(fri, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 310, -1));

        political.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                politicalActionPerformed(evt);
            }
        });
        jPanel1.add(political, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, 310, -1));

        nati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                natiActionPerformed(evt);
            }
        });
        jPanel1.add(nati, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 310, -1));

        etha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ethaActionPerformed(evt);
            }
        });
        jPanel1.add(etha, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 310, -1));

        reli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reliActionPerformed(evt);
            }
        });
        jPanel1.add(reli, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, 310, -1));

        tami_ca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tami_caActionPerformed(evt);
            }
        });
        jPanel1.add(tami_ca, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 580, 310, -1));

        muslim_scep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muslim_scepActionPerformed(evt);
            }
        });
        jPanel1.add(muslim_scep, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 620, 310, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Whatsapp Link");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 720, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Viber");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 760, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Twitter");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 800, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Intagram");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 840, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Snap Chat");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 880, -1, -1));

        whats_app_link.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whats_app_linkActionPerformed(evt);
            }
        });
        jPanel1.add(whats_app_link, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 720, 390, -1));

        viber_link.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viber_linkActionPerformed(evt);
            }
        });
        jPanel1.add(viber_link, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 760, 390, -1));

        twitter_link.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twitter_linkActionPerformed(evt);
            }
        });
        jPanel1.add(twitter_link, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 800, 390, -1));

        insta_link.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insta_linkActionPerformed(evt);
            }
        });
        jPanel1.add(insta_link, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 840, 390, -1));

        snap_link.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snap_linkActionPerformed(evt);
            }
        });
        jPanel1.add(snap_link, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 880, 390, -1));

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Socal Media Links", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 680, 540, 260));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Face Book Videos");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 930, -1, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Face Book Imagers");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 850, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Face book Pagers");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 890, -1, -1));

        fb_ima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_imaActionPerformed(evt);
            }
        });
        jPanel1.add(fb_ima, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 850, 250, -1));

        fb_pa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_paActionPerformed(evt);
            }
        });
        jPanel1.add(fb_pa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 890, 250, -1));

        fb_video.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb_videoActionPerformed(evt);
            }
        });
        jPanel1.add(fb_video, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 930, 250, -1));

        jLabel40.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FB Details Count", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 810, 570, 160));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Profile Pic Date");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1050, -1, -1));

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.LONG))));
        jPanel1.add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1050, 260, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Profile Image");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 1050, -1, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Discription");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1200, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1200, 940, 140));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Analize");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1410, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1410, 940, 140));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Validated By");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 1600, -1, -1));
        jPanel1.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1600, 270, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 1720, 240, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 1720, 220, 40));
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 1040, 290, 150));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Choose");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 1040, 110, 40));

        jLabel46.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profile Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1000, 1130, 830));

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1303, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1921, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fb_paActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_paActionPerformed
        fb_video.grabFocus();
    }//GEN-LAST:event_fb_paActionPerformed

    private void fb_imaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_imaActionPerformed
        fb_pa.grabFocus();
    }//GEN-LAST:event_fb_imaActionPerformed

    private void snap_linkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snap_linkActionPerformed
        fb_ima.grabFocus();
    }//GEN-LAST:event_snap_linkActionPerformed

    private void insta_linkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insta_linkActionPerformed
        snap_link.grabFocus();
    }//GEN-LAST:event_insta_linkActionPerformed

    private void twitter_linkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twitter_linkActionPerformed
        insta_link.grabFocus();
    }//GEN-LAST:event_twitter_linkActionPerformed

    private void viber_linkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viber_linkActionPerformed
        twitter_link.grabFocus();
    }//GEN-LAST:event_viber_linkActionPerformed

    private void whats_app_linkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whats_app_linkActionPerformed
        viber_link.grabFocus();
    }//GEN-LAST:event_whats_app_linkActionPerformed

    private void muslim_scepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muslim_scepActionPerformed
        whats_app_link.grabFocus();
    }//GEN-LAST:event_muslim_scepActionPerformed

    private void tami_caActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tami_caActionPerformed
        muslim_scep.grabFocus();
    }//GEN-LAST:event_tami_caActionPerformed

    private void reliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reliActionPerformed
        tami_ca.grabFocus();
    }//GEN-LAST:event_reliActionPerformed

    private void ethaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ethaActionPerformed
        reli.grabFocus();
    }//GEN-LAST:event_ethaActionPerformed

    private void natiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_natiActionPerformed
        etha.grabFocus();
    }//GEN-LAST:event_natiActionPerformed

    private void politicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_politicalActionPerformed
        nati.grabFocus();
    }//GEN-LAST:event_politicalActionPerformed

    private void friActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friActionPerformed
        political.grabFocus();
    }//GEN-LAST:event_friActionPerformed

    private void re_linkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re_linkActionPerformed
        fri.grabFocus();
    }//GEN-LAST:event_re_linkActionPerformed

    private void re_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re_typeActionPerformed
        re_link.grabFocus();
    }//GEN-LAST:event_re_typeActionPerformed

    private void re_fb_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re_fb_idActionPerformed
        re_type.grabFocus();
    }//GEN-LAST:event_re_fb_idActionPerformed

    private void re_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re_nameActionPerformed
        re_fb_id.grabFocus();
    }//GEN-LAST:event_re_nameActionPerformed

    private void OccupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OccupActionPerformed
        jComboBox1.grabFocus();
    }//GEN-LAST:event_OccupActionPerformed

    private void locaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locaActionPerformed
        Occup.grabFocus();
    }//GEN-LAST:event_locaActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        loca.grabFocus();
    }//GEN-LAST:event_cityActionPerformed

    private void discActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discActionPerformed
        city.grabFocus();
    }//GEN-LAST:event_discActionPerformed

    private void bornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bornActionPerformed
        disc.grabFocus();
    }//GEN-LAST:event_bornActionPerformed

    private void gradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradActionPerformed
        born.grabFocus();
    }//GEN-LAST:event_gradActionPerformed

    private void univerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_univerActionPerformed
        grad.grabFocus();
    }//GEN-LAST:event_univerActionPerformed

    private void hi_schhoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hi_schhoolActionPerformed
        univer.grabFocus();
    }//GEN-LAST:event_hi_schhoolActionPerformed

    private void schoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolActionPerformed
        hi_schhool.grabFocus();
    }//GEN-LAST:event_schoolActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        school.grabFocus();
    }//GEN-LAST:event_emailActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        email.grabFocus();
    }//GEN-LAST:event_contactActionPerformed

    private void fb_nic_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_nic_namActionPerformed
        contact.grabFocus();
    }//GEN-LAST:event_fb_nic_namActionPerformed

    private void fb_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_nameActionPerformed
        fb_nic_nam.grabFocus();
    }//GEN-LAST:event_fb_nameActionPerformed

    private void fb_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_idActionPerformed
        fb_name.grabFocus();
    }//GEN-LAST:event_fb_idActionPerformed

    private void fb_videoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb_videoActionPerformed
        jFormattedTextField2.grabFocus();
    }//GEN-LAST:event_fb_videoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            if (fb_id.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Face Book Id Cannot be Empty");
            } else if (fb_name.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Face book Name Cannot be Empty");
            } else if (fb_nic_nam.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Face Book Nick name Cannot be Empty");
            } else if (email.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Number Cannot be Empty");
            } else if (contact.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Contact Cannot be Empty");
            } else if (school.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "School Name Cannot be Empty");
            } else if (hi_schhool.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "High School Name Cannot be Empty");
            } else if (univer.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "University Cannot be Empty");
            } else if (grad.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Graduade Cannot be Empty");
            } else if (born.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Born State Cannot be Empty");
            } else if (disc.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Distric Cannot be Empty");
            } else if (city.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "City Cannot be Empty");
            } else if (loca.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Location Cannot be Empty");
            } else if (Occup.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Occupations Cannot be Empty");
                /*----------marid enwa----------*/
            } else if (year.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Year Cannot be Empty");
            } else if (re_fb_id.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Relative's Id Cannot be Empty");
            } else if (re_name.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Relative's Name Cannot be Empty");
            } else if (re_type.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Relative's Type Cannot be Empty");
            } else if (re_link.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Relative's Link Cannot be Empty");
            } else if (fri.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Friends Cannot be Empty");
            } else if (political.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Political Cannot be Empty");
            } else if (nati.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "National Cannot be Empty");
            } else if (etha.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ethancity Cannot be Empty");
            } else if (reli.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Religion Cannot be Empty");
            } else if (tami_ca.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tamil Cast Cannot be Empty");
            } else if (muslim_scep.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Muslim Scep Cannot be Empty");
            } else if (whats_app_link.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Whatsapp Link Cannot be Empty");
            } else if (viber_link.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Viber Cannot be Empty");
            } else if (twitter_link.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Twitter Cannot be Empty");
            } else if (insta_link.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Intagram Cannot be Empty");
            } else if (snap_link.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Snap Chat Cannot be Empty");
            } else if (fb_ima.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Face Book Imagers Cannot be Empty");
            } else if (fb_pa.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Face book Pagers Cannot be Empty");
            } else if (fb_video.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Face Book Videos Cannot be Empty");
            } else {
                thinethra_DBClass.iud("insert into register value('" + fb_id.getText() + "','" + fb_name.getText() + "','" + fb_nic_nam.getText() + "','" + email.getText() + "','" + contact.getText() + "','" + school.getText() + "','" + hi_schhool.getText() + "','" + univer.getText() + "','" + grad.getText() + "','" + born.getText() + "','" + disc.getText() + "','" + city.getText() + "','" + loca.getText() + "','" + Occup.getText() + "','" + jComboBox1.getSelectedItem() + "','" + year.getText() + "','" + re_fb_id.getText() + "','" + re_name.getText() + "', '" + re_type.getText() + "','" + re_link.getText() + "','" + fri.getText() + "','" + political.getText() + "','" + nati.getText() + "','" + etha.getText() + "','" + reli.getText() + "','" + tami_ca.getText() + "','" + muslim_scep.getText() + "','" + whats_app_link.getText() + "','" + viber_link.getText() + "','" + twitter_link.getText() + "','" + insta_link.getText() + "','" + snap_link.getText() + "','" + fb_ima.getText() + "','" + fb_pa.getText() + "','" + fb_video.getText() + "', '" + login.user_id + "' )");
                thinethra_DBClass.iud("INSERT INTO profile_details(register_fb_id,profile_pic) VALUES('" + fb_id.getText() + "','" + newpath + "') ");
                clearFeailds();

            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed

    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            JFileChooser jf = new JFileChooser(new File("C:\\Users\\ABC\\Pictures"));
            int x = jf.showOpenDialog(this);
            if (x == jf.APPROVE_OPTION) {
                File f1 = jf.getSelectedFile();
                String path = f1.getAbsolutePath();
                newpath = path.replace("\\", "/");
                f1 = new File(newpath);
                Image i = ImageIO.read(f1);
                i = i.getScaledInstance(jLabel47.getWidth(), jLabel47.getHeight(), Image.SCALE_SMOOTH);
                jLabel47.setIcon(new ImageIcon(i));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Search();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Occup;
    private javax.swing.JTextField born;
    private javax.swing.JTextField city;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField disc;
    private javax.swing.JTextField email;
    private javax.swing.JTextField etha;
    private javax.swing.JTextField fb_id;
    private javax.swing.JTextField fb_ima;
    private javax.swing.JTextField fb_name;
    private javax.swing.JTextField fb_nic_nam;
    private javax.swing.JTextField fb_pa;
    private javax.swing.JTextField fb_video;
    private javax.swing.JTextField fri;
    private javax.swing.JTextField grad;
    private javax.swing.JTextField hi_schhool;
    private javax.swing.JTextField insta_link;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField loca;
    private javax.swing.JTextField muslim_scep;
    private javax.swing.JTextField nati;
    private javax.swing.JTextField political;
    private javax.swing.JTextField re_fb_id;
    private javax.swing.JTextField re_link;
    private javax.swing.JTextField re_name;
    private javax.swing.JTextField re_type;
    private javax.swing.JTextField reli;
    private javax.swing.JTextField school;
    private javax.swing.JTextField snap_link;
    private javax.swing.JTextField tami_ca;
    private javax.swing.JTextField twitter_link;
    private javax.swing.JTextField univer;
    private javax.swing.JTextField viber_link;
    private javax.swing.JTextField whats_app_link;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables

    private void clearFeailds() {
        try {
            fb_id.setText(null);
            fb_name.setText(null);
            fb_nic_nam.setText(null);
            contact.setText(null);
            email.setText(null);
            school.setText(null);
            hi_schhool.setText(null);
            univer.setText(null);
            grad.setText(null);
            born.setText(null);
            disc.setText(null);
            city.setText(null);
            loca.setText(null);
            Occup.setText(null);
            year.setText(null);
            re_name.setText(null);
            re_fb_id.setText(null);
            re_type.setText(null);
            re_link.setText(null);
            fri.setText(null);
            political.setText(null);
            nati.setText(null);
            etha.setText(null);
            reli.setText(null);
            tami_ca.setText(null);
            muslim_scep.setText(null);
            whats_app_link.setText(null);
            viber_link.setText(null);
            twitter_link.setText(null);
            insta_link.setText(null);
            snap_link.setText(null);
            fb_ima.setText(null);
            fb_pa.setText(null);
            fb_video.setText(null);
            jLabel47.setIcon(null);
            newpath = "-";

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void Search() {

        try {
            ResultSet rs = thinethra_DBClass.search("SELECT * FROM register r,profile_details d WHERE r.fb_id = d.register_fb_id AND r.fb_id = '" + fb_id.getText() + "' ");
            if (rs.next()) {
                fb_name.setText(rs.getString("fb_name"));
                fb_nic_nam.setText(rs.getString("fb_nick_name"));
                contact.setText(rs.getString("contact_num"));
                email.setText(rs.getString("fb_email"));
                school.setText(rs.getString("schools"));
                hi_schhool.setText(rs.getString("high_schools"));
                univer.setText(rs.getString("university"));
                grad.setText(rs.getString("graduate"));
                born.setText(rs.getString("born_country"));
                disc.setText(rs.getString("state"));
                city.setText(rs.getString("current_city"));
                loca.setText(rs.getString("location"));
                Occup.setText(rs.getString("occupation"));
                year.setText(rs.getString("year"));
                re_name.setText(rs.getString("rele_name"));
                re_fb_id.setText(rs.getString("rela_id"));
                re_type.setText(rs.getString("rele_type"));
                re_link.setText(rs.getString("rele_link"));
                fri.setText(rs.getString("fri_count"));
                political.setText(rs.getString("political"));
                nati.setText(rs.getString("nationality"));
                etha.setText(rs.getString("ethanicity"));
                reli.setText(rs.getString("religion"));
                tami_ca.setText(rs.getString("tamil_cast"));
                muslim_scep.setText(rs.getString("muslims_sec"));
                whats_app_link.setText(rs.getString("whats_app_link"));
                viber_link.setText(rs.getString("viber_link"));
                twitter_link.setText(rs.getString("twitter_link"));
                insta_link.setText(rs.getString("insta_link"));
                snap_link.setText(rs.getString("snapchat_link"));
                fb_ima.setText(rs.getString("fb_images"));
                fb_pa.setText(rs.getString("fb_pagers"));
                fb_video.setText(rs.getString("fb_videos"));
                loadImage(rs.getString("profile_pic"));
                
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void loadImage(String path) {
        
        try {
            File f = new File(path);

            if (f.exists()) {

                Image i = ImageIO.read(f);
                i = i.getScaledInstance(199, 151, Image.SCALE_SMOOTH);
                jLabel47.setIcon(new ImageIcon(i));

            } else {
                //System.out.println("Image not found!");    
                jLabel47.setText("Image Not Found!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
